import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#051424',
        primary: '#fbfffa',
        'primary-fixed-dim': '#00e1ab',
        'primary-fixed': '#36ffc4',
        'primary-container': '#00ffc2',
        'on-primary': '#003828',
        'on-primary-fixed': '#002116',
        'on-primary-fixed-variant': '#00513c',
        'on-primary-container': '#007255',
        'inverse-primary': '#006c50',
        'surface-tint': '#00e1ab',
        surface: '#051424',
        'surface-dim': '#051424',
        'surface-bright': '#2c3a4c',
        'surface-container-lowest': '#010f1f',
        'surface-container-low': '#0d1c2d',
        'surface-container': '#122131',
        'surface-container-high': '#1c2b3c',
        'surface-container-highest': '#273647',
        'surface-variant': '#273647',
        'inverse-surface': '#d4e4fa',
        'inverse-on-surface': '#233143',
        'on-surface': '#d4e4fa',
        'on-surface-variant': '#b9cbc1',
        'on-background': '#d4e4fa',
        outline: '#83958c',
        'outline-variant': '#3a4a43',
        secondary: '#c8c6c5',
        'secondary-container': '#474746',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary': '#313030',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474746',
        'on-secondary-container': '#b7b5b4',
        tertiary: '#fffeff',
        'tertiary-container': '#ffe149',
        'tertiary-fixed': '#ffe253',
        'tertiary-fixed-dim': '#e2c62e',
        'on-tertiary': '#393000',
        'on-tertiary-fixed': '#211b00',
        'on-tertiary-fixed-variant': '#534600',
        'on-tertiary-container': '#746300',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        'margin-desktop': '32px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
    },
  },
  plugins: [],
} satisfies Config;
